name: Tests

on:
  push:
    branches-ignore:
      - "translations"
      - "dependabot/**"
  pull_request:

jobs:
  run:
    name: Node on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: npm

      - run: java -version

      - name: Install npm dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: |
          echo "::add-matcher::.github/workflows/remark-lint-problem-matcher.json"
          npm test

      - name: Run HTML validator
        run: npm run test:html

      - name: Run linkinator
        run: npm run test:linkinator
